### ISSUE TITLE
Realizar pantalla de partida

### ISSUE THREAD

**Issue by DavidArruga** [UNIZAR-30226-2023-03/frontend-web#4]
Poder mover las fichas en función del número sacado en el dado.

**Comment by TorkiTorki** [comment]
las fichas se mueven a lugar esperado, falta conectar el comportamiento con el backend

**Comment by DavidArruga** [comment]
Comportamiento con el backend realizado con éxito.
Falta mostrar las fichas bloqueadas mediante una x encima.

**Comment by DavidArruga** [comment]
Movimiento de fichas y timer terminado

**Comment by DavidArruga** [comment]
Falta realizar el chat y los ajustes.

**Comment by DavidArruga** [comment]
Chat terminado.
Falta la ventana de ajustes.

**Comment by DavidArruga** [comment]
Ventana de  ajustes realizada.
Falta probar la desconexión con el backend.

**Comment by DavidArruga** [comment]
Pantalla finalizada
